# Schema for the configuration files of uwauth module.
uwauth.settings:
  type: config_object
  mapping:
    group:
      type: 'mapping'
      label: 'Groups'
      mapping:
        source:
          type: 'string'
          label: 'Source'
    mail:
      label: 'E-mail settings'
      type: 'mapping'
      mapping:
        valid_domains:
          type: 'sequence'
          label: 'Valid email domains'
          nullable: true
          sequence:
            type: 'string'
            label: 'Domain'
            translatable: false
